import { chromium } from "playwright-core";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1600, height: 900 } });
await p.goto("http://localhost:8123/#/");
await p.waitForTimeout(700);
await p.screenshot({ path: "/tmp/proof/50_lock_wash.png" });
await p.waitForTimeout(700);
await p.screenshot({ path: "/tmp/proof/51_lock_wash2.png" });
await p.waitForTimeout(600);
await p.screenshot({ path: "/tmp/proof/52_lock_white.png" });
await p.waitForTimeout(400);
await p.screenshot({ path: "/tmp/proof/53_lock_exit.png" });
await b.close();
console.log("lockup shots done");
